GET http://127.0.0.1:5000/hello
accept: application/json

###

POST http://127.0.0.1:5000/auth/token
content_type: application/json

{
    "username": "poc",
    "password": "xogene5!"
}

###

POST http://127.0.0.1:5000/conversation
content_type: application/json
accept: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyNywidXNlcm5hbWUiOiJwb2MiLCJleHAiOjE2NzgzNzYyNDN9.NYZ6ivVFcimAZqJ_20Y9B6zkpWC51iEKU1S3cWf9itk

{
    "promptHeader": "Act as an experienced Nurse... ",
    "initialMessage": "Hello, would you like to know if you qualify for this trial?",
    "userRoleName": "Patient",
    "botRoleName": "Nurse",
    "conversationHistory": [
        {
            "userMessage": "yes", 
            "userMessageTimeStamp": 1,
            "response": "Are you older than 12 years of ag?",
            "responseTimeStamp": 2
        },
        {
            "userMessage": "yes", 
            "userMessageTimeStamp": 3,
            "response": "Are you in good health?",
            "responseTimeStamp": 4
        }
    ],
    "userMessage": "Yes"
}

###

GET http://127.0.0.1:5000/login?username=cliff&password=cmr
accept: application/json

###

GET http://127.0.0.1:5000/domain/30
accept: application/json

###
POST http://127.0.0.1:5000/answer
content_type: application/json
accept: application/json

{
    "domain_id": 7,
    "query": "what kind of site is this",
    "prompt_text": "Answer the question from the context.  context: <<CONTEXT>> question: <<QUESTION>>",
    "user_id": 1,
    "temp": 0.4
}

###
POST http://127.0.0.1:5000/hello
content_type: application/x-www-form-urlencoded

data=hey
