#http://xogene-01.eba-zdq22h3k.us-east-1.elasticbeanstalk.com/auth/token
#https://api.trippersalmanac.com/hello

GET http://127.0.0.1:5000/hello
accept: application/json

###

POST http://127.0.0.1:5000/auth/token
content-type: application/json
accept: application/json

{
    "username": "poc",
    "password": "xogene5!"
}

###

POST http://127.0.0.1:5000
content-type: application/json
accept: application/json

{
    "username": "poc",
    "password": "xogene5!"
}

###

POST http://127.0.0.1:5000/conversation
content-type: application/json
accept: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyNywidXNlcm5hbWUiOiJwb2MiLCJleHAiOjE2NzgzODU0NDF9.9PgZpJhFzQIpcbEIMEMODr727srblfg4qPwVc4qaOz0

{
    "promptHeader": "Act as an experienced Nurse... ",
    "initialMessage": "Hello, would you like to know if you qualify for this trial?",
    "userRoleName": "Patient",
    "botRoleName": "Nurse",
    "conversationHistory": [
        {
            "userMessage": "yes", 
            "userMessageTimeStamp": 1,
            "response": "Are you older than 12 years of ag?",
            "responseTimeStamp": 2
        },
        {
            "userMessage": "yes", 
            "userMessageTimeStamp": 3,
            "response": "Are you in good health?",
            "responseTimeStamp": 4
        }
    ],
    "userMessage": "Yes"
}

###

GET http://127.0.0.1:5000/login?username=cliff&password=cmr
accept: application/json

###

GET http://127.0.0.1:5000/domain/30
accept: application/json

###
#POST http://xogene-01.eba-zdq22h3k.us-east-1.elasticbeanstalk.com/answer
POST http://127.0.0.1:5000/answer
content-type: application/json
accept: application/json

{
    "conversation_id": "NEW",
    "domain_id": 30,
    "user_id": 1,
    "query": "hello",
    "prompt_template": "Answer the question as honestly as you can.",
    "temp": 0.4
}

