GET http://127.0.0.1:5000/hello
accept: application/json

###

GET http://127.0.0.1:5000/login?username=cliff&password=cmr
accept: application/json

###

GET http://127.0.0.1:5000/domain
accept: application/json

###
POST http://127.0.0.1:5000/answer
content_type: application/json
accept: application/json

{
    "domain_id": 7,
    "query": "what kind of site is this",
    "prompt_text": "Answer the question from the context.  context: <<CONTEXT>> question: <<QUESTION>>",
    "user_id": 1,
    "temp": 0.4
}

###
POST http://127.0.0.1:5000/hello
content_type: application/x-www-form-urlencoded

data=hey
